serverAddr = ""
serverPort = 7000
dnsServer = "114.114.114.114"

[log]
level = "debug"
disablePrintColor = true

[[visitors]]
name = "p2p_visitor"
type = "xtcp"
serverName = ""
secretKey = ""
bindAddr = "127.0.0.1"
bindPort = 6000